version: '2'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - TZ=Japan
      - MYSQL_DATABASE=feedich
      - MYSQL_USER=feedich
      - MYSQL_PASSWORD=feedich
      - MYSQL_ROOT_PASSWORD=root
