SESSION_ID="B98FCBAF30202AD501CDDF05D1B29221"

curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=ansible&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=https://www.osstech.co.jp/~hamano/index.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=%E3%83%93%E3%83%83%E3%82%B0%E3%83%87%E3%83%BC%E3%82%BF&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://crumbjp.hateblo.jp/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=slack&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=https://matsumana.info/atom.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://line-hr.jp/atom.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://blog-at.line.me/index.rdf" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://blog.livedoor.jp/m-32_19196/index.rdf" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://blog.ymda.jp/feed/atom/" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://adobeurawaza.blog57.fc2.com/?xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://javascripter.hatenablog.com/feed/category/%E5%88%9D%E3%82%81%E3%81%A6%E3%81%AEJavaScript" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/octech/searchdiary?word=%2A%5Bruby%5D&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://blog.goo.ne.jp/ruby-philia/index.rdf" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://mizutanisakura.sblo.jp/index20.rdf" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://aramaruweb.blog83.fc2.com/?xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://blog.64p.org/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://official-blog.line.me/ja/index.rdf" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://www.yasuhisay.info/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://mattintosh.hatenablog.com/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://backpaper0.github.io/rss.html" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://yomon.hatenablog.com/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=linux&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=Java&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://moznion.hatenadiary.com/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://bufferings.hatenablog.com/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://walking-gourmet.hateblo.jp/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=python&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=docker&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=https://srad.jp/sradjp.rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://n-agetsuma.hatenablog.com/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://linefukuoka.blog.jp/index.rdf" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://atsuizo.hatenadiary.jp/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://news.livedoor.com/topics/rss/love.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=monitoring&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=zookeeper&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=fluentd&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=line&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://portal.nifty.com/rss/headline.rdf" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=hive&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=grafana&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://kaigai.hatenablog.com/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=ambari&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=presto&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=https://blogs.apache.org/planet/feed/entries/atom" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/cartooh/rss2" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=prometheus&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=network&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=dbms&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=elasticsearch&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=hadoop&amp;users=5&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=https://www.ibm.com/developerworks/jp/views/rss/customrssatom.jsp?zone_type=AllZones&amp;content_type=AllTypes&amp;search_by=&amp;day=1&amp;month=01&amp;year=2008&amp;max_entries=10&amp;feed_by=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=vue.js&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=kerberos&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=bigdata&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://katsumakazuyo.hatenablog.com/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?safe=on&amp;q=%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/hotentry/it.rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://fxkinri.blog56.fc2.com/?xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://g5mac.blog76.fc2.com/?xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://blog.livedoor.jp/staff_reader/atom.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feed.japan.cnet.com/rss/index.rdf" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://gigazine.net/news/rss_2.0/" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://creeper.no-ip.info/adiary/rss.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/fromdusktildawn/rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://www.100shiki.com/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://www.popxpop.com/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://blog.livedoor.jp/kazu_fujisawa/index.rdf" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/tihara/rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://remote.seesaa.net/index.rdf" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://nanigashi3.blog40.fc2.com/?xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feeds.feedburner.com/Lifehackingjp" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://mala.tumblr.com/rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feeds.feedburner.com/hatena/b/hotentry" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://blog.livedoor.jp/ume3_/index.rdf" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feeds.feedburner.com/mala/blog" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://shinta.tea-nifty.com/nikki/atom.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://rss.rssad.jp/rss/itmatmarkit/rss.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://www.yukawanet.com/sunday/index.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://blog.livedoor.jp/lalha/atom.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://satoshi.blogs.com/life/index.rdf" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://blog.livedoor.jp/kensuu/index.rdf" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://jkondo.hatenablog.com/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/wanwangorogoro/rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/umedamochio/rss2" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feeds.feedburner.com/csseliteshowcase" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://www.webdedb.com/index.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feeds.feedburner.com/luckybag" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feeds.feedburner.com/phpspot/ccuf" | jq .
#curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://hail2u.net/blog/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feeds.feedburner.com/caramel_vanilla" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://www.bebit.co.jp/memo/index.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://my-chunqiu.cocolog-nifty.com/blog/index.rdf" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://www.geekpage.jp/rss.php" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://www.ideaxidea.com/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feeds.feedburner.com/csshappylife" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feeds.feedburner.com/StopnListen" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://mb.blog7.fc2.com/?xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://www.coolwebwindow.com/weblife_column/index.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feeds.feedburner.com/webblog" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feeds.feedburner.com/designwalker" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feeds.feedburner.com/creamu/hLkA" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://webos-goodies.jp/index.rdf" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://xxsionxx.blog17.fc2.com/?xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://blog.creamu.com/designhacks/atom.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://www.hamashun.com/blog/atom.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feeds.feedburner.com/EmotionalWeb" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feeds.feedburner.com/Webajax" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://www.jam-graffiti.com/non-pic-css/latest-topics.rdf" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feeds.feedburner.com/RedlineMagazine/" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://www.webdesignlibrary.jp/index.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://note.openvista.jp/feed/" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://accessibility.mitsue.co.jp/index.rdf" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://www.click-assist.com/blog/xml-rss1.php" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/amachang/rss2" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/mailishmaid/rss2" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://rubyist.g.hatena.ne.jp/d4-1977/rss2" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/rubyco/rss2" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://foxkeh.jp/feed/" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/gan2/rss2" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://ruby.g.hatena.ne.jp/garyo/rss2" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feeds.feedburner.com/designwalker_seed/" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://kagamihoge.hatenablog.com/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://rss.rssad.jp/rss/codezine/new/20/index.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/higayasuo/rss2" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://rss.rssad.jp/rss/doruby/blog/feed_all" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feeds.feedburner.com/h2ham" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://gura5.blog120.fc2.com/?xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://www.rubyist.net/~matz/index.rdf" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/gtaka555/rss2" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/tek_koc/rss2" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feeds.feedburner.com/recompile/rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/Yoshiori/rss2" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feeds.feedburner.com/Yoshiori" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/japanrock_pg/rss2" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://b.hatena.ne.jp/search/tag?q=ruby&amp;mode=rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/rubikitch/rss2" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/naoya/rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/sobolog/rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/dice-x/rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/takisawa/rss2" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://blog.livedoor.jp/dqnplus/index.rdf" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://news23vip.blog109.fc2.com/?xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://kaisun1192.blog121.fc2.com/?xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://blog.hacklife.net/atom.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://www.uka-blog.com/feed/" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://rubyist.g.hatena.ne.jp/teraco/rss2" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://feeds.feedburner.com/bulknews" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/xlovecallx/rss2" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/lovecall/rss2" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/khiker/rss2" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/adda/rss" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://www.simplexsimple.com/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://rss.rssad.jp/rss/oshietekun/atom.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://secondlife.hatenablog.jp/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://level.s69.xrea.com/mozilla/rss.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://blog.kentarok.org/feed" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://blog.livedoor.jp/nipotan/atom.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://www.oreilly.co.jp/catalog/soon.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://rssblog.ameba.jp/argv/rss20.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://greasemonkey.blog67.fc2.com/?xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://yohei-y.blogspot.com/atom.xml" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://blog.livedoor.jp/dankogai/index.rdf" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://d.hatena.ne.jp/kwatch/rss2" | jq .
curl -X PUT http://localhost:8080/api/subscriptions -b FEEDICH=${SESSION_ID} --data-urlencode "feedUrl=http://www.ryuzee.com/contents/blog/feed" | jq .
