export const SET_SUBSCRIPTIONS = 'SET_SUBSCRIPTIONS'
export const SUBSCRIBE = 'SUBSCRIBE'
export const UNSUBSCRIBE = 'UNSUBSCRIBE'
export const READ_ITEM = 'READ_ITEM'
export const UNREAD_ITEM = 'UNREAD_ITEM'

export const SET_PINS = 'SET_PINS'
export const ADD_PIN = 'ADD_PIN'
export const REMOVE_PIN = 'REMOVE_PIN'
export const CLEAR_PINS = 'CLEAR_PINS'
